version: '2.1'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: line_redis
  app:
    restart: always
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - '8000:8000'
    expose:
      - '8000'
    volumes:
      - ${PWD}:/app
      - ${PWD}/nltk_data:/root/nltk_data
    depends_on:
      - redis 
    stdin_open: true
    tty: true
    container_name: line_api
